## Global Args
ARG UID=1000
ARG GID=1000

## Build stage
FROM ghcr.io/trillon008/healthcheck:1.0.0 AS healthcheck
FROM registry.access.redhat.com/ubi10/go-toolset:10.1 AS builder

ARG RELEASE=2.11.3
ARG CADDY_VERSION=v2.11.3
ARG XCADDY_VERSION=v0.4.5
ARG CADDY_OVH_VERSION=v1.1.0

# Build caddy with the OVH DNS module.
RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@${XCADDY_VERSION}
RUN "$(go env GOPATH)/bin/xcaddy" build ${CADDY_VERSION} \
    --with github.com/caddy-dns/ovh@${CADDY_OVH_VERSION}


## Image stage
FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1

RUN microdnf install -y ca-certificates tzdata && \
    microdnf clean all && \
    mkdir -p /caddy/etc  /caddy/var && \
    chown -R ${UID}:${GID} /caddy

COPY --from=builder /opt/app-root/src/caddy /usr/bin/caddy
COPY --from=healthcheck /healthcheck /usr/local/bin/healthcheck

WORKDIR /caddy
EXPOSE 80 443 2019
USER ${UID}:${GID}

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["run", "--config", "/caddy/etc/Caddyfile", "--adapter", "caddyfile"]
