FROM registry.access.redhat.com/ubi10/go-toolset:10.1 AS builder

WORKDIR /src

COPY go.mod main.go ./

RUN mkdir -p /tmp/out && \
    CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /tmp/out/healthcheck ./main.go

FROM scratch

COPY --from=builder /tmp/out/healthcheck /healthcheck
ENTRYPOINT ["/healthcheck"]
